### ISSUE TITLE
Question about DI to application from domain

### ISSUE THREAD

**Issue by bacebu4** [rasouza/node-clean-architecture#4]
Is that really necessary to inject domain entities into application layer? I thought it was alright to import from the inner layer 

I'm new to the app's architecture, would be glad to read the explanation

Thanks in advance!

**Comment by rasouza** [comment]
Hey, thanks for asking and sorry the late reply! Now onto the question itself...

Looking only at the functionality point of view, importing and injecting would have exactly the same effect for the domain doesn't need to be "bootstrapped" in the container (they are all simple entities). Although there are a couple of things to take into consideration as well: testing and standardization (the first being the main reason).

You'll probably want to be able to mock in an easy way all external dependencies when unit testing your application layer, otherwise your code will end up having a hard dependency (you should avoid that as much as possible). 

Moreover, in order to improve readability, you can check all dependencies of a given use case all in one place: the arguments of that injection function `({ UserRepository, User })`. I believe it would be a little odd to have `UserRepository` injection while importing `User` domain at the same time:

```js
const User = require('...')
module.exports = ({ UserRepository }) => ...
```

Of course you can make trade-offs here to best suit your needs (or coding style). This template also has some of its own.

**Comment by bacebu4** [comment]
Thanks a lot! Got your point now 

And yeah, for unit testing it is essential thing to mock every dependency so that makes a lot of sense here. Haven't considered it by myself cause I am only getting into writing unit tests
