### ISSUE TITLE
Mongo patch and post is not working 

### ISSUE THREAD

**Issue by sivaraj-v** [rasouza/node-clean-architecture#5]
Hi @rasouza  

You're doing a great job, but I've discovered that the patch and post functions in the mangoose database aren't working.
Please update and revalidate it.

**Comment by rasouza** [comment]
Hey, sorry taking so long for a simple issue.

I see your point, the problem was that both POST and PATCH was working properly but the API wasn't raising the exceptions properly.

You can test again and you'll see the validation errors pop up. Also you can run `yarn test` to make sure the HTTP verbs are working properly

I'm closing this issue but feel free to reopen it if you will
